[features]
seeds = true
skip-lint = false
init_if_needed=true
[programs.localnet]
potluck = "PoTeh9dW9VEr6ApxiLintTRoWmZDF6GDRrtSu7zbTo4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/akshay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
