[features]
seeds = true
skip-lint = false
init_if_needed=true
[programs.localnet]
potluck = "PoTeh9dW9VEr6ApxiLintTRoWmZDF6GDRrtSu7zbTo4"

[programs.devnet]
potluck = "PoTeh9dW9VEr6ApxiLintTRoWmZDF6GDRrtSu7zbTo4"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
# wallet = "/mnt/d/01-HEMP-CITY/06-mint-candy-machines/wh-new-authority-wallet.json"
cluster = "localnet"
wallet = "/home/akshay/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
